name: YoSoCool
favicon: null
layout_spectrum: 0.16188267059624195
typography_spectrum: 0.8115467999596149
title: 'Yo So Cool Frozen Yogurt!'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000f1f'
    - '#e7e8ea'
    - '#b08a39'
    - '#4689cd'
    - '#982316'
  brandStrength: 0.08722925744950771
  lightness: 0.7861441692803055
  saturation: 0.9986050731968135
  rhythmicContrast: 0.9055973119102418
purpose: []
